export const seminarList = [
  {
    image: 'https://s3-ap-southeast-1.amazonaws.com/blockchain-academy-static/seminar-bitcoin.jpg',
    name: 'Introduction to Bitcoin and Blockchain ครั้งที่ 1',
    venue: 'HUBBA-TO',
    shortDescription:
        'คอร์สอบรมความรู้ระดับเบื้องต้นเกี่ยวกับ Bitcoin และ Blockchain พร้อมสาธิตการเทรด' +
        'และการขุด',
    longDescription: '<p>เพื่อให้สอดคล้องกับภารกิจข<wbr />องเราในการทำให้เทคโนโลยี Blockchain และ Cryptocurrency สามารถถูกเข้าถึงและเป็นที่<wbr />นิยมมากขึ้นในประเทศไทย และเพื่อให้คนไทยมีความรู้แ<wbr />ละความเข้าใจในเทคโนโลยีดัง<wbr />กล่าวจนกระทั่งสามารถนำไปต่<wbr />อยอดให้เกิดเป็นประโยชน์ต่อ<wbr />ตนเองและผู้อื่นได้สูงสุด ทาง Siam Blockchain จึงจัดตอร์สคอร์สฝึกอบรมด้า<wbr />น Blockchain และ Cryptocurrency สำหรับผู้ที่ไม่เคยมีความรู้ในด้านนี้มาก่อน แต่มีความสนใจอย่างจริงจัง และกำลังมองหาหลักสูตรแบบรว<wbr />บรัดที่มีผู้เชี่ยวชาญเข้าม<wbr />าช่วยดูแลในด้านนี้ โดยทางวิทยากรณ์นั้นจะเป็นนั<wbr />กเขียนและทีมงานของ SiamBlockchain ได้แก่ คุณพีรพัฒน์ หาญคงแก้ว หรือ คุณหาญ และ คุณณัฐชนน โพธิ์เงิน หรือ คุณเอิธ โดยทั้งสองมีประสบการณ์และเ<wbr />คยไปบรรยายในงานสัมนาที่จัด<wbr />โดย<br /><br />- Pantip<br />- Biostar<br />- Thminer<br /><br />Bitcoin คืออะไร?<br />เงินดิจิตอลปลอดภัยจริงหรือ<wbr />ไม่?<br />ทำไม Bitcoin ถึงมีมูลค่า?<br />Blockchain เอาไว้ทำอะไร?<br />นี่ใช่แชร์ลูกโซ่รึเปล่า?<br /><br />Siam Blockchain เว็บข่าวสาร Blockchain และ Cryptocurrency เพื่อคนไทย จะขอมาตอบคำถามของทุกท่านผ่<wbr />านคอร์สเรียน &ldquo;Introduction to Bitcoin and Blockchain&rdquo; ที่จะทำการมอบความรู้เกี่ยว<wbr />กับเงินดิจิตอล เทคโนโลยี Blockchain และ Cryptocurrency เพื่อให้เกิดความเข้าใจ และรู้เท่าทันกับเทคโนโลยีท<wbr />ี่เป็นที่พูดถึงกันทั่วโลกใ<wbr />นขณะนี้<br /><br />ความรู้ที่ผู้เข้าร่วมทุกท่<wbr />านจะได้รับหลังจากคอร์สนี้ คือ<br /><br />จุดกำเนิด และที่มาที่ไปของ Bitcoin<br />ความเข้าใจเกี่ยวกับหลักการ<wbr />ทำงานของ Bitcoin และ Blockchain รวมถึงบทบาทของเทคโนโลยีเหล<wbr />่านี้ในชีวิตของเรา<br />รู้จักกับการขุด Bitcoin และ Cryptocurrency รวมถึงกลไกเบื้องหลังของการ<wbr />ขุด<br />รู้เท่าทันถึงอันตราย และความเสี่ยงจากเงินดิจิตอ<wbr />ล รวมถึงวิธีป้องกันตนเองจากภ<wbr />ัยอันตรายเหล่านี้<br />รู้จักตลาด และช่องทางในการลงทุน Cryptocurrency<br />ประสบการ์ณในการเทรดและขุดข<wbr />องวิทยากรทั้งสองท่าน<br />Demo วิธีการเทรดและการโอนเงินเบื้องต้น<br />Demo การขุด โดยเราจะนำเครื่องขุดแบบริก<wbr />มา Demo ให้ดูว่ามันทำงานยังไง พร้อมแมนวลวิธีการขุด<br />Q&amp;A Session สุดพิเศษกับ 2 วิทยากร<br />โดยการจัดทำคอร์สนี้ เป็นการมุ่งหวังเพื่อสร้างค<wbr />วามรู้ และความเข้าใจในเทคโนโลยีนี<wbr />้อย่างกว้างขวางมากขึ้นในปร<wbr />ะเทศไทย<br /><br />คอร์สนี้เป็นการโครงการนำร่<wbr />องหากได้ผลตอบรับดีเราอาจจะ<wbr />พิจารณาในคอร์สถัดๆไป เช่น<br /><br />การทำกำไรด้วยการขุดแบบเชิง<wbr />ลึก และวิธีการคำนวณ<br />การเทรดเบื้องต้น/เชิงลึก<br />ICO<br />การเขียนโปรแกรมเกี่ยวกับ Blockchain<br />Ethereum<br />Smart Contract<br />ประโยชน์ของเทคโนโลยี Blockchain ที่มีต่อองค์กร<br />การสร้างเงินดิจิตอล<br />วันและเวลา: วันอาทิตย์ที่ 29 ตุลาคม 2560 เวลา 13.00 &ndash; 17.00<br />สถานที่: HUBBA-TO Screening room อ่อนนุช <a href="https://l.facebook.com/l.php?u=https%3A%2F%2Ftinyurl.com%2Fycqxecno&amp;h=ATNplB4QYxV0UrM-ssN93Yz3p_9fHkJJVhw__EdWLzr17GvUL5Fj0EuR0ZJFB0BBRxJw1lLyfp55IEdGgDsOpHMyQ0qQ4D7hEDwl81_4sv4wobeBW2Q34IUzWkB-AywULVVsNwsdLkmvh9vsenRY9GsuSc6NZFC7CpEYMk17sCDQBn6202SUsps" target="_blank" rel="nofollow noopener" data-lynx-mode="async">https://tinyurl.com/<wbr />ycqxecno</a><br />ค่าสมัคร: 1,499 บาท<br />งานสัมนานี้สำหรับ: มือใหม่<br /><br />*สำหรับผู้ที่ลงชื่อในงานนี้<wbr />เราจะมีส่วนลดให้ในคอร์สถั<wbr />ดไป<br /><br />รับจำนวนจำกัดเพียง 50 ที่นั่ง<br />มีอาหารว่างให้<br />สำหรับผู้ที่ต้องการบิลหรือ<wbr />ใบเสร็จกรุณาแจ้งล่วงหน้า<br /><br />หากมีข้อสงสัยสามารถติดต่อไ<wbr />ด้ที่เพจ Siam Blockchain หรือ 080-962-6306 (คุณหาญ)</p>',
    time: '29 October 2017',
    price: '1,499 THB',
    slug: 'introduction-to-bitcoin-and-blockchain-1',
    facebookEventLink: 'https://www.facebook.com/events/123928214983178/',
    ratings: {
      ความเหมาะสมของสถานที่จัดงาน: 4,
      ความเหมาะสมแก่การเดินทาง: 3.7,
      วิทยากรสามารถถ่ายทอดความรู้ได้เหมาะสมเพียงใด: 4,
      บรรยากาศในการอบรมมีความเหมาะสมเพียงใด: 4,
      ท่านได้รับความรู้จากคอร์สนี้เพียงใด: 3.9,
      ท่านสามารถนำความรู้ที่ได้จากคอร์สนี้ไปต่อยอดได้เพียงใด: 3.7,
    },
    reviews: [
      'ประทับใจการตอบคำถาม ที่สามารถตอบคำถามได้เป็นอย่างดี',
      'อธิบายเข้าใจง่าย',
      'รูปแบบของสไลด์ดูง่ายดี',
      'ระยะเวลา หัวข้อ ไม่สอดคล้องกัน',
      'สถานที่จัดไกลไปหน่อย',
    ],
    maxParticipants: 50,
    actualParticipants: 50,
  },
  {
    image: 'https://s3-ap-southeast-1.amazonaws.com/blockchain-academy-static/seminar-bitcoin-2.jpg',
    name: 'Introduction to Bitcoin and Blockchain ครั้งที่ 2',
    venue: 'สมาคมธรรมศาสตร์',
    longDescription: '<p>Bitcoin คืออะไร?<br /><br />เงินดิจิตอลปลอดภัยจริงหรือ<wbr />ไม่?<br /><br />ทำไม Bitcoin ถึงมีมูลค่า?<br /><br />Blockchain เอาไว้ทำอะไร?<br /><br />นี่ใช่แชร์ลูกโซ่รึเปล่า?<br /><br />Siam Blockchain เว็บข่าวสาร Blockchain และ Cryptocurrency เพื่อคนไทย จะขอมาตอบคำถามของทุกท่านผ่<wbr />านคอร์สเรียน "Introduction to Bitcoin and Blockchain" ที่จะทำการมอบความรู้เกี่ยว<wbr />กับเงินดิจิตอล เทคโนโลยี Blockchain และ Cryptocurrency เพื่อให้เกิดความเข้าใจ และรู้เท่าทันกับเทคโนโลยีท<wbr />ี่เป็นที่พูดถึงกันทั่วโลกใ<wbr />นขณะนี้<br /><span class="text_exposed_show"><br />- ความรู้ที่ผู้เข้าร่วมทุกท่<wbr />านจะได้รับหลังจากคอร์สนี้ คือ<br />- จุดกำเนิด และที่มาที่ไปของ Bitcoin<br />- ความเข้าใจเกี่ยวกับหลักการ<wbr />ทำงานของ Bitcoin และ Blockchain รวมถึงบทบาทของเทคโนโลยีเหล<wbr />่านี้ในชีวิตของเรา<br />- รู้จักกับการขุด Bitcoin และ Cryptocurrency รวมถึงกลไกเบื้องหลังของการ<wbr />ขุด<br />- รู้เท่าทันถึงอันตราย และความเสี่ยงจากเงินดิจิตอ<wbr />ล รวมถึงวิธีป้องกันตนเองจากภ<wbr />ัยอันตรายเหล่านี้<br />- รู้จักตลาด และช่องทางในการลงทุน Cryptocurrency<br />- ประสบการ์ณในการเทรดและขุดข<wbr />องวิทยากรทั้งสองท่าน<br />- Demo วิธีการเทรดและการโอนเงินเบ<wbr />ื้องต้น<br />- Demo การขุด โดยเราจะนำเครื่องขุดมา Demo ให้ดูว่ามันทำงานยังไง พร้อมแมนวลวิธีการขุด<br />- Q&amp;A Session สุดพิเศษกับ 2 วิทยากร<br /><br />เนื้อหาและจุดประสงค์ในการจ<wbr />ัดทำคอร์สนี้ เป็นการมุ่งหวังเพื่อสร้างค<wbr />วามรู้ และความเข้าใจในเทคโนโลยีนี<wbr />้อย่างกว้างขวางมากขึ้นในปร<wbr />ะเทศไทย โดยเนื้อหาในคอร์สนี้จะมีทั<wbr />้งเรื่องเทคโนโลยีและการลงท<wbr />ุนแต่จะเน้นไปที่พื้นฐานของ<wbr />ความเข้าใจในตัวของ Bitcoin และ Blockchain<br /><br />โดยการจัดอบรมคอร์สนี้ เป็นการจัดงานครั้งที่ 2 แล้ว เพื่อตอบสนองความต้องการจำน<wbr />วนมากของผู้สนใจที่ต้องการค<wbr />้นหาและได้รับความรู้เกี่ยว<wbr />กับ Bitcoin และ Blockchain<br /><br />วันและเวลา: วันเสาร์ที่ 18 พฤศจิกายน 2560 เวลา 13.00 - 17.00<br /><br />สถานที่: สมาคมธรรมศาสตร์ Auditoruim พระราม 4&nbsp;<a href="https://l.facebook.com/l.php?u=https%3A%2F%2Ftinyurl.com%2Fyd97nhoa&amp;h=ATNRXBryIJ9MoKo09bjdPh765zPQVDKpWScpfgRO35MRL9THuPgynu7myhHKasmi-w-imeTwggpAyW2GLcAECEcPYpbM06rCIgT0fkyO-rujAmCy0FbpAQItKqHutOUciqnmY9ZjTXD9gXtkrLOMgw6ouNv-OlrjSbFJ60QBj7YifzZ9rMqkm-E" target="_blank" rel="nofollow noopener" data-lynx-mode="async">https://tinyurl.com/<wbr />yd97nhoa</a><br /><br />ค่าสมัคร: 1,799 บาท<br /><a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.zipeventapp.com%2Fe%2FIntroduction-to-Bitcoin-and-Blockchain-2rd-by-Siam-Blockchain&amp;h=ATO-EhfcEaL_PuXFLTM73z-ayjaeF1rknZkDCjxFblUkeRrJH7Px686-IT9LvFvUjQeHefivI7BqDyFP4JvwYsztlkmz2Fgx21vegWJ5hu--Xn886zC5MUbKD08J6pTMj_OHjQqzWXvZ9QwhaZYjcYoLQnBwHiNWj9tpVoUqUxVpHC6d-cY4hME" target="_blank" rel="nofollow noopener" data-lynx-mode="async">https://<wbr />www.zipeventapp.com/e/<wbr />Introduction-to-Bitcoin-and<wbr />-Blockchain-2rd-by-Siam-Bl<wbr />ockchain</a><br /><br />งานสัมนานี้สำหรับ: มือใหม่<br />มีอาหารว่างให้<br /><br /><br />ความประทับใจบางส่วนจากผู้เ<wbr />ข้าร่วมในคอร์สที่แล้ว<br /><br />"เข้าใจเรื่องของ Bitcoin มากขึ้น"<br /><br />"รู้จักสกุลเงินดิจิตอลมากข<wbr />ึ้น"<br /><br />"บรรยากาศเป็นกันเองดี"<br /><br />"รูปแบบของสไลด์ที่ดูง่ายดี<wbr />"<br /><br />"ความเชี่ยวชาญของวิทยากร"<br /><br />"อธิบายเข้าใจง่าย"<br /><br /><br />หากมีข้อสงสัยสามารถติดต่อไ<wbr />ด้ที่เพจ Siam Blockchain หรือ 080-962-6306 (คุณหาญ)</span></p>',
    shortDescription:
        'คอร์สอบรมความรู้ระดับเบื้องต้นเกี่ยวกับ Bitcoin และ Blockchain พร้อมสาธิตการเทรด' +
        'และการขุด',
    time: '18 November 2017',
    price: '1,799 THB',
    slug: 'introduction-to-bitcoin-and-blockchain-2',
    facebookEventLink: 'https://www.facebook.com/events/225354634665078/',
    ratings: {
      ความเหมาะสมของสถานที่จัดงาน: 4.2,
      ความเหมาะสมแก่การเดินทาง: 3.7,
      วิทยากรสามารถถ่ายทอดความรู้ได้เหมาะสมเพียงใด: 4.3,
      บรรยากาศในการอบรมมีความเหมาะสมเพียงใด: 4.2,
      ท่านได้รับความรู้จากคอร์สนี้เพียงใด: 4.2,
      ท่านสามารถนำความรู้ที่ได้จากคอร์สนี้ไปต่อยอดได้เพียงใด: 4.1,
      ความคุ้มค่าต่อราคาคอร์ส: 3.9,
      รสชาติอาหารว่าง: 3.6,
    },
    reviews: [
      'บรรยากาศเป็นกันเอง',
      'ได้รับความรู้ใหม่ๆ ที่บางอย่างเรานึกว่ารู้แล้ว เราก็ยังไม่รู้ และอาจารย์เรียงเนื้อหาคอร์สดี ปูทางให้เข้าใจแต่ละจุดได้ง่าย',
      'รายละเอียดครบถ้วน วิทยากรพูดเข้าใจง่ายและมีตัวอย่างทำให้เห็นภาพและเข้าใจง่าย',
      'วิทยากรมีการลำดับเรื่องการบรรยายได้ดี มีการเว้นช่วงให้ถามตอบ',
      'เป็นกันเองดี  ใส่ใจตอบทุกคำถามมากครับ',
      'บางครั้งใช้ศัทพ์ทางเทคนิคมากไป',
      'อยากให้สถานที่ติด MRT กับ BTS มากกว่านี่ เข้าซอยมาค่อนข้างลำบาก',
    ],
    maxParticipants: 160,
    actualParticipants: 77,
  },
];
